# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Test-5-7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Test-5-7
pod "PGFramework"
  target 'Test-5-7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Test-5-7UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
